name: Next.js 14 CI (npm)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install next-seo @types/next-seo --save-dev
          npx update-browserslist-db@latest

      - name: Configure ESLint for Next.js 14
        run: |
          echo '{
            "extends": "next/core-web-vitals",
            "rules": {
              "import/no-anonymous-default-export": "off",
              "@next/next/no-img-element": "warn"
            }
          }' > .eslintrc.json

      - name: Build with Next.js
        run: npm run build

      - name: Run type checking
        run: npm run type-check

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next
